version: '3.8'
services:
  app:
    build:
      context: .
    command: >
      sh -c "
      python manage.py wait_for_db &&
      python manage.py collectstatic &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - ./staticfiles:/staticfiles
    environment:
      - DEBUG=1
      - SECRET_KEY=thesecretkey
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devdbuser
      - DB_PASS=devdbpassword
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devdbuser
      - POSTGRES_PASSWORD=devdbpassword