version: '3.8'
services:
  app:
    build: .
    volumes:
      - ./:/digi_tp
    ports:
      - 8000:8000
    image: digi_tp:1.0
    container_name: digi_tp_vehicle_management
    command: gunicorn digi_tp.wsgi:application --bind 0.0.0.0:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=thesecretkey
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devdbuser
      - DB_PASS=devdbpassword
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: always
    container_name: digi_tp_vehicle_management_db
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devdbuser
      - POSTGRES_PASSWORD=devdbpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data/