# Generated by Django 4.2 on 2023-04-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number_plate", models.CharField(max_length=50)),
                ("nick_name", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
