# Generated by Django 4.2 on 2023-04-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicle", "0001_vehicles_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="vehcile_model",
            field=models.CharField(
                choices=[("model s", "Model S"), ("super custome", "Super Custome")],
                default="default model",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="vehcile_type",
            field=models.CharField(
                choices=[("toyota", "Toyata"), ("tesla", "Tesla")], default="default type", max_length=50
            ),
        ),
    ]
