# Generated by Django 4.2 on 2023-04-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicle", "0002_add_vehicle_model_and_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="vehcile_model",
            field=models.CharField(
                choices=[("Super Custom", "Super Custome"), ("prado", "Prado")], default="default model", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vehcile_type",
            field=models.CharField(
                choices=[("Suv", "Suv"), ("Toyota", "Toyota")], default="default type", max_length=50
            ),
        ),
    ]
