# Generated by Django 4.2 on 2023-04-29 22:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_customuser_options_customusermanager"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUserManager",
        ),
    ]
