# Generated by Django 4.2 on 2023-04-29 22:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_delete_customusermanager"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
    ]
