# Generated by Django 4.2 on 2023-04-29 22:53

from django.db import migrations
import user.models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_alter_customuser_options"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", user.models.CustomUserManager()),
            ],
        ),
    ]
