# Generated by Django 4.2 on 2023-04-30 08:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_alter_customuser_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
